### ISSUE TITLE
Not compile from delphinus in tokio 10.2

### ISSUE THREAD

**Issue by MaxCppX72** [SynEdit/SynEdit#70]
base must be exactly overlapping with folder string to remove it

**Comment by Memnarch** [comment]
One Entry in the delphinus script uses a DOT, instead of the correct path for the base.

**Comment by amjadtbssm** [comment]
Which entry **Memnarch** please clarify

**Comment by Pawe1** [comment]
BTW - why the only available release in SynEdit reposiroty is not even a stable one?... :roll_eyes:

**Comment by CWBudde** [comment]
I have updated the Delphinus.json file now and created a new release. Hopefully it is satisfying. If anyone wants to improve it further, feel free to do so and send a PR, I'll surely merge it.

**Comment by Memnarch** [comment]
@CWBudde the json references nonexisting projects. Everything beyond XE8 is missing in the repository(like subfolders RX1, RX2 in Packages)

**Comment by CWBudde** [comment]
Indeed, I'll fix that

**Comment by Memnarch** [comment]
i should write a tool that helps with creating and validating (basic) packages oO

**Comment by CWBudde** [comment]
This would help a lot, especially for maintainers that do not have more than one Delphi versions installed.

**Comment by Memnarch** [comment]
i looked abit through the file and i think it needs to be modified differently. You copy the sourcefolder but not the packages. So here is my proposal:
Change the copy operation like this:
`  "source_folders": [{
    "folder": ".",
    "recursive": true,
    "filter": "*"
  }],`
This should copy everything. It will not lift up the source-folder but simple is better at this point i think.

**Comment by Memnarch** [comment]
that worked like a charm! I suggest to recreate the new release. This issue seems to be solved

**Comment by amjadtbssm** [comment]
Download SynEdit as ZIP from main page, modify the Delphinus.Install.json as follows (Simple copy the whole thing posted here and paste it in existing file **Do not forget to clear the file contents**) add Lib path and It will work like a charm.
`{
        "search_pathes": 
    [
        {
            "pathes": "Source;Source",
            "platforms": "Win32"
        }
    ],
    "browsing_pathes": 
    [
        {
            "pathes": "Source;Packages;Demos;SynGen",
            "platforms": "Win32"
        }
    ],

    "source_folders":
    [        
		{
            "folder": "Source",
            "base": "Source",
            "recursive": true,
            "filter": "*.*;*"
        },
		{
            "folder": "Source",
            "base": ".",
            "recursive": true,
            "filter": "*.*;*"
        },
	   {
			"folder": "Packages",
			"base": ".",
			"recursive": true,
			"filter": "*.*;*"
		},	
		{
			"folder": "Demos",
			"base": ".",
			"recursive": true,
			"filter": "*.*;*"
		},
		{
			"folder": "SynGen",
			"base": ".",
			"recursive": true,
			"filter": "*.*;*"
		}		
    ],

	"projects":
	[
		{
			"project": "Packages\\2010\\SynEdit.groupproj",
			"compiler_min": 21,
			"compiler_max": 21
		},
		{
			"project": "Packages\\XE\\SynEdit.groupproj",
			"compiler_min": 22,
			"compiler_max": 22
		},
		{
			"project": "Packages\\XE2\\SynEdit.groupproj",
			"compiler_min": 23,
			"compiler_max": 23
		},
		{
			"project": "Packages\\XE3\\SynEdit.groupproj",
			"compiler_min": 24,
			"compiler_max": 24
		},
		{
			"project": "Packages\\XE4\\SynEdit.groupproj",
			"compiler_min": 25,
			"compiler_max": 25
		},
		{
			"project": "Packages\\XE5\\SynEdit.groupproj",
			"compiler_min": 26,
			"compiler_max": 26
		},
		{
			"project": "Packages\\XE6\\SynEdit.groupproj",
			"compiler_min": 27,
			"compiler_max": 27
		},
		{
			"project": "Packages\\XE7\\SynEdit.groupproj",
			"compiler_min": 28,
			"compiler_max": 28
		},
		{
			"project": "Packages\\XE8\\SynEdit.groupproj",
			"compiler_min": 29,
			"compiler_max": 29
		},
		{
			"project": "Packages\\10S\\SynEdit.groupproj",
			"compiler_min": 30,
			"compiler_max": 30
		},
		{
			"project": "Packages\\101B\\SynEdit.groupproj",
			"compiler_min": 31,
			"compiler_max": 31
		},
		{
			"project": "Packages\\102T\\SynEdit.groupproj",
			"compiler_min": 32,
			"compiler_max": 32		
		}
	]
}`

**Comment by Memnarch** [comment]
@amjadtbssm it is already fixed

**Comment by amjadtbssm** [comment]
@Memnarch I have been writing without refreshing the page ;-)

**Comment by CWBudde** [comment]
I close this for now as being resolved. If there are further problems, I'll reopen it again.

**Comment by Memnarch** [comment]
i propose to simply recreate the 2.10 beta release on head and remove the 2.11 beta.

**Comment by CWBudde** [comment]
Done, I wasn't aware of the fact that it is possible to delete and recreate existing releases.

**Comment by Memnarch** [comment]
But not correct. For both releases 2.10 and 2.11 you have to remove the release AND the Tag. And then create the 2.10 release again(a release requires a tag, if that tag does not exist, it is created on HEAD). RN you created the 2.10 release on the same old commit/tag(and the tag for 2.11 still exists)

**Comment by CWBudde** [comment]
I never stop learning. Thanks for the detailed description. I followed it closely now and truly recreated that new release

**Comment by Memnarch** [comment]
Perfect! Thanks for your time :)
One little thing left is to remove the broken older release 2.09(which does not work in Delphinus). You can either just delete the release here on github OR use the first_version property with the value of SynEdit-2.1.0-beta in the info.json. That commit does not need to be in a release(HEAD is sufficcient to be used by Delphinus). WIth both ways, you can remove the release from Delphinus (in case you choose to simply delete the broken one: just keep in mind to NOT delete future releases from Delphinus. Just in this broken case, it is ok)
